"""Initial migration

Revision ID: efe53c4cae73
Revises: f42b21bc7342
Create Date: 2024-06-30 22:16:48.309118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe53c4cae73'
down_revision: Union[str, None] = 'f42b21bc7342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interface_info',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('requestParams', sa.Text(), nullable=False),
    sa.Column('requestHeader', sa.Text(), nullable=True),
    sa.Column('responseHeader', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=256), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.Column('isDelete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interface_info_id'), 'interface_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interface_info_id'), table_name='interface_info')
    op.drop_table('interface_info')
    # ### end Alembic commands ###
