"""Initial migration

Revision ID: f42b21bc7342
Revises: 
Create Date: 2024-06-30 17:35:47.383913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42b21bc7342'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('userName', sa.String(length=256), nullable=True),
    sa.Column('userAccount', sa.String(length=256), nullable=False),
    sa.Column('userAvatar', sa.String(length=1024), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('userRole', sa.String(length=256), nullable=False),
    sa.Column('userPassword', sa.String(length=512), nullable=False),
    sa.Column('accessKey', sa.String(length=512), nullable=False),
    sa.Column('secretKey', sa.String(length=512), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.Column('isDelete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userAccount')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
